import { ValueBar } from "../common_widgets.slint";
import { Theme } from "../globals.slint";
import { AboutSlint } from "std-widgets.slint";

export component PageAbout inherits VerticalLayout {
    padding: 10px;
    spacing: 10px;
    Text {
        vertical-alignment: TextVerticalAlignment.center;
        horizontal-alignment: TextHorizontalAlignment.center;
        text: "A UI for asusctl made with slint";
        font-size: 22px;
    }

    Text {
        vertical-alignment: TextVerticalAlignment.center;
        horizontal-alignment: TextHorizontalAlignment.center;
        text: "Work in progress";
        font-size: 22px;
    }
}
