import { AboutSlint, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component PageAbout inherits VerticalLayout {
    padding: 10px;
    spacing: 10px;
    Text {
        vertical-alignment: TextVerticalAlignment.center;
        horizontal-alignment: TextHorizontalAlignment.center;
        text: "A UI for asusctl made with slint";
        font-size: 22px;
    }

    HorizontalBox {
        alignment: LayoutAlignment.center;
        VerticalBox {
            alignment: LayoutAlignment.center;

            Text {
                wrap: TextWrap.word-wrap;
                text: "You will require these patches: https://lore.kernel.org/platform-driver-x86/20240404001652.86207-1-luke@ljones.dev/, they have been merged upstream for kernel 6.10. The main thing is that the PPT settings will apply without them, but the read/back will fail";
            }

            Text {
                vertical-alignment: TextVerticalAlignment.center;
                horizontal-alignment: TextHorizontalAlignment.center;
                text: "Todo:";
                font-size: 22px;
            }

            Text {
                text: "- [x] Theme the widgets";
            }

            Text {
                text: "- [x] Add a fullscreen mode (cli arg)";
            }

            Text {
                text: "- [x] Disable aura items depending if mode supports or not";
            }

            Text {
                text: "- [x] Add fan curve graph controls";
            }

            Text {
                text: "- [ ] Add a cpu/gpu temp/fan speed info bar";
            }

            Text {
                text: "- [ ] Supergfx control";
            }

            Text {
                text: "- [ ] Include fan speeds, temps in a bottom bar";
            }

            Text {
                text: "- [ ] Screenpad controls";
            }

            Text {
                text: "- [ ] ROG Ally specific settings";
            }
        }
    }

    Text {
        vertical-alignment: TextVerticalAlignment.center;
        horizontal-alignment: TextHorizontalAlignment.center;
        text: "Work in progress";
        font-size: 22px;
    }
}
