import { Theme } from "../globals.slint";

export component PageFans inherits VerticalLayout {
    Rectangle {
        clip: true;
        // TODO: slow with border-radius
        padding: 8px;
        // height: parent.height - infobar.height - mainview.padding - self.padding * 2;
        // TODO: border-radius: 8px;
        mainview := VerticalLayout {
            padding: 10px;
            spacing: 10px;
            Text {
                text: "TODO";
            }
        }
    }
}
