/*
 Generated by typeshare 1.7.0
*/

export enum AnimBooting {
	GlitchConstruction = "GlitchConstruction",
	StaticEmergence = "StaticEmergence",
}

export enum AnimAwake {
	BinaryBannerScroll = "BinaryBannerScroll",
	RogLogoGlitch = "RogLogoGlitch",
}

export enum AnimSleeping {
	BannerSwipe = "BannerSwipe",
	Starfield = "Starfield",
}

export enum AnimShutdown {
	GlitchOut = "GlitchOut",
	SeeYa = "SeeYa",
}

export interface Animations {
	boot: AnimBooting;
	awake: AnimAwake;
	sleep: AnimSleeping;
	shutdown: AnimShutdown;
}

/** Base LED brightness of the display */
export enum Brightness {
	Off = "Off",
	Low = "Low",
	Med = "Med",
	High = "High",
}

export interface DeviceState {
	display_enabled: boolean;
	display_brightness: Brightness;
	builtin_anims_enabled: boolean;
	builtin_anims: Animations;
	off_when_unplugged: boolean;
	off_when_suspended: boolean;
	off_when_lid_closed: boolean;
	brightness_on_battery: Brightness;
}

export enum AnimeType {
	GA401 = "GA401",
	GA402 = "GA402",
	GU604 = "GU604",
	Unknown = "Unknown",
}

