/*
 Generated by typeshare 1.7.0
*/

export enum GpuMode {
	Discrete = "Discrete",
	Optimus = "Optimus",
	Integrated = "Integrated",
	Egpu = "Egpu",
	Vfio = "Vfio",
	Ultimate = "Ultimate",
	Error = "Error",
	NotSupported = "NotSupported",
}

export enum PlatformPolicy {
	Balanced = "Balanced",
	Performance = "Performance",
	Quiet = "Quiet",
}

/** CamelCase names of the properties. Intended for use with DBUS */
export enum Properties {
	ChargeControlEndThreshold = "ChargeControlEndThreshold",
	DgpuDisable = "DgpuDisable",
	GpuMuxMode = "GpuMuxMode",
	PostAnimationSound = "PostAnimationSound",
	PanelOd = "PanelOd",
	MiniLedMode = "MiniLedMode",
	EgpuEnable = "EgpuEnable",
	PlatformPolicy = "PlatformPolicy",
	PptPl1Spl = "PptPl1Spl",
	PptPl2Sppt = "PptPl2Sppt",
	PptFppt = "PptFppt",
	PptApuSppt = "PptApuSppt",
	PptPlatformSppt = "PptPlatformSppt",
	NvDynamicBoost = "NvDynamicBoost",
	NvTempTarget = "NvTempTarget",
}

