/*
 Generated by typeshare 1.6.0
*/

export type AnimeSupportedFunctions = boolean;

export interface ChargeSupportedFunctions {
	charge_level_set: boolean;
}

export interface PlatformProfileFunctions {
	platform_profile: boolean;
	fan_curves: boolean;
}

export enum AdvancedAura {
	None = "None",
	Zoned = "Zoned",
	PerKey = "PerKey",
}

export interface LedSupportedFunctions {
	dev_id: AuraDevice;
	brightness: boolean;
	basic_modes: AuraModeNum[];
	basic_zones: AuraZone[];
	advanced_type: AdvancedAura;
	power_zones: PowerZones[];
}

export interface RogBiosSupportedFunctions {
	post_sound: boolean;
	gpu_mux: boolean;
	panel_overdrive: boolean;
	dgpu_disable: boolean;
	egpu_enable: boolean;
	mini_led_mode: boolean;
}

export interface SupportedFunctions {
	anime_ctrl: AnimeSupportedFunctions;
	charge_ctrl: ChargeSupportedFunctions;
	platform_profile: PlatformProfileFunctions;
	keyboard_led: LedSupportedFunctions;
	rog_bios_ctrl: RogBiosSupportedFunctions;
}

export enum GpuMode {
	Discrete = "Discrete",
	Optimus = "Optimus",
	Integrated = "Integrated",
	Egpu = "Egpu",
	Vfio = "Vfio",
	Ultimate = "Ultimate",
	Error = "Error",
	NotSupported = "NotSupported",
}

