/*
 Generated by typeshare 1.6.0
*/

export enum FanCurvePU {
	CPU = "CPU",
	GPU = "GPU",
}

export interface CurveData {
	fan: FanCurvePU;
	pwm: [number, number, number, number, number, number, number, number];
	temp: [number, number, number, number, number, number, number, number];
}

/** A `FanCurveSet` contains both CPU and GPU fan curve data */
export interface FanCurveSet {
	enabled: boolean;
	cpu: CurveData;
	gpu: CurveData;
}

/** Main purpose of `FanCurves` is to enable restoring state on system boot */
export interface FanCurveProfiles {
	balanced: FanCurveSet;
	performance: FanCurveSet;
	quiet: FanCurveSet;
}

export enum Profile {
	Balanced = "Balanced",
	Performance = "Performance",
	Quiet = "Quiet",
}

