/*
 Generated by typeshare 1.7.0
*/

export enum FanCurvePU {
	CPU = "CPU",
	GPU = "GPU",
	MID = "MID",
}

export interface CurveData {
	fan: FanCurvePU;
	pwm: [number, number, number, number, number, number, number, number];
	temp: [number, number, number, number, number, number, number, number];
	enabled: boolean;
}

/** Main purpose of `FanCurves` is to enable restoring state on system boot */
export interface FanCurveProfiles {
	balanced: CurveData[];
	performance: CurveData[];
	quiet: CurveData[];
}

