#!/bin/sh
rm -rf _build
mkdir -p _build/modules
mkdir -p _build/bindings
cp -r target/modules/*js _build/modules/
cp -r target/bindings/*.js _build/bindings/
cp -r metadata.json schemas target/*.js _build
# cp -r icons resources *.css _build
# cp src/prefs.ui _build/

exit 0;