//! # D-Bus interface proxy for: `xyz.ljones.Backlight`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection
//! data. Source: `Interface '/xyz/ljones' from service 'xyz.ljones.Asusd' on
//! system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the
//! zbus documentation.
//!
//! This type implements the [D-Bus standard interfaces],
//! (`org.freedesktop.DBus.*`) for which the following zbus API can be used:
//!
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "xyz.ljones.Backlight",
    default_service = "xyz.ljones.Asusd",
    default_path = "/xyz/ljones"
)]
pub trait Backlight {
    /// PrimaryBrightness property
    #[zbus(property)]
    fn primary_brightness(&self) -> zbus::Result<i32>;
    #[zbus(property)]
    fn set_primary_brightness(&self, value: i32) -> zbus::Result<()>;

    /// ScreenpadBrightness property
    #[zbus(property)]
    fn screenpad_brightness(&self) -> zbus::Result<i32>;
    #[zbus(property)]
    fn set_screenpad_brightness(&self, value: i32) -> zbus::Result<()>;

    /// ScreenpadGamma property
    #[zbus(property)]
    fn screenpad_gamma(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_screenpad_gamma(&self, value: &str) -> zbus::Result<()>;

    /// ScreenpadPower property
    #[zbus(property)]
    fn screenpad_power(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_screenpad_power(&self, value: bool) -> zbus::Result<()>;

    /// ScreenpadSyncWithPrimary property
    #[zbus(property)]
    fn screenpad_sync_with_primary(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_screenpad_sync_with_primary(&self, value: bool) -> zbus::Result<()>;
}
