//! # `DBus` interface proxy for: `xyz.ljones.Asusd`
//!
//! This code was generated by `zbus-xmlgen` `1.0.0` from `DBus` introspection
//! data. Source: `Interface '/xyz/ljones/Platform' from service
//! 'xyz.ljones.Asusd' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://zeenix.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!
//! This `DBus` object implements
//! [standard `DBus` interfaces](https://dbus.freedesktop.org/doc/dbus-specification.html),
//! (`org.freedesktop.DBus.*`) for which the following zbus proxies can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! …consequently `zbus-xmlgen` did not generate code for the above interfaces.

use rog_platform::cpu::CPUEPP;
use rog_platform::platform::{Properties, ThrottlePolicy};
use zbus::proxy;

#[proxy(
    interface = "xyz.ljones.Platform",
    default_service = "xyz.ljones.Asusd",
    default_path = "/xyz/ljones"
)]
pub trait Platform {
    #[zbus(property)]
    fn version(&self) -> zbus::Result<String>;

    /// NextThrottleThermalPolicy method
    fn next_throttle_thermal_policy(&self) -> zbus::Result<()>;

    /// SupportedProperties method
    fn supported_properties(&self) -> zbus::Result<Vec<Properties>>;

    /// ChargeControlEndThreshold property
    #[zbus(property)]
    fn charge_control_end_threshold(&self) -> zbus::Result<u8>;
    #[zbus(property)]
    fn set_charge_control_end_threshold(&self, value: u8) -> zbus::Result<()>;

    // Toggle one-shot charge to 100%
    fn one_shot_full_charge(&self) -> zbus::Result<()>;

    /// ThrottleBalancedEpp property
    #[zbus(property)]
    fn throttle_balanced_epp(&self) -> zbus::Result<CPUEPP>;
    #[zbus(property)]
    fn set_throttle_balanced_epp(&self, epp: CPUEPP) -> zbus::Result<()>;

    /// ThrottlePerformanceEpp property
    #[zbus(property)]
    fn throttle_performance_epp(&self) -> zbus::Result<CPUEPP>;
    #[zbus(property)]
    fn set_throttle_performance_epp(&self, epp: CPUEPP) -> zbus::Result<()>;

    /// ThrottlePolicyLinkedEpp property
    #[zbus(property)]
    fn throttle_policy_linked_epp(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_throttle_policy_linked_epp(&self, value: bool) -> zbus::Result<()>;

    /// ThrottlePolicyOnAc property
    #[zbus(property)]
    fn throttle_policy_on_ac(&self) -> zbus::Result<ThrottlePolicy>;
    #[zbus(property)]
    fn set_throttle_policy_on_ac(&self, throttle_policy: ThrottlePolicy) -> zbus::Result<()>;

    /// ChangeThrottlePolicyOnAc property
    #[zbus(property)]
    fn change_throttle_policy_on_ac(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_change_throttle_policy_on_ac(&self, change: bool) -> zbus::Result<()>;

    /// ThrottlePolicyOnBattery property
    #[zbus(property)]
    fn throttle_policy_on_battery(&self) -> zbus::Result<ThrottlePolicy>;
    #[zbus(property)]
    fn set_throttle_policy_on_battery(&self, throttle_policy: ThrottlePolicy) -> zbus::Result<()>;

    /// ChangeThrottlePolicyOnAc property
    #[zbus(property)]
    fn change_throttle_policy_on_battery(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_change_throttle_policy_on_battery(&self, change: bool) -> zbus::Result<()>;

    /// ThrottleQuietEpp property
    #[zbus(property)]
    fn throttle_quiet_epp(&self) -> zbus::Result<CPUEPP>;
    #[zbus(property)]
    fn set_throttle_quiet_epp(&self, epp: CPUEPP) -> zbus::Result<()>;

    /// ThrottlePolicy property
    #[zbus(property)]
    fn throttle_thermal_policy(&self) -> zbus::Result<ThrottlePolicy>;
    #[zbus(property)]
    fn set_throttle_thermal_policy(&self, throttle_policy: ThrottlePolicy) -> zbus::Result<()>;
}
